version: "3"
services:
  chrome:
    image: kasmweb/chrome:1.16.1
    container_name: kasm_chrome
    shm_size: "512m"
    restart: always
    ports:
      - "6901:6901"
    environment:
      - VNC_PW=
      - KASM_VNC_PW=
      - DISABLE_CLIPBOARD=0
      - DISABLE_DOWNLOAD=0 
      - DISABLE_UPLOAD=0
      - START_PULSEAUDIO=0
      - KASM_AUTH=basic
      - KASM_MENU=0
    command: ["--no-auth"]
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2'
    logging:
      options:
        max-size: "10m"
        max-file: "3" 